# Override the envFrom field to exclude 'artifactory-share'
extraEnvVarsCM:
  - inji-stack-config
  - config-server-share

istio:
  enabled: false  # Disables VirtualService creation if Istio is used

virtualService:
  enabled: false  # Explicitly disable VirtualService if applicable

service:
  enabled: true   # Ensure service is still enabled, if needed