#image:
#  registry: docker.io
#  repository: mosipdev/partner-onboarder
#  tag: develop

### If you are running Mimoto Onboarder in a separate inji cluster where PMS or Keycloak doesn't exist,
### then uncomment lines 8 to 25 and update the values accordingly.
#extraEnvVarsCM: []
#extraEnvVarsSecret: []
#extraEnvVars:
#  - name: installation-domain
#    value: dev.mosip.net
#  - name: mosip-api-host
#    value: api.dev.mosip.net
  #### pms domain
#  - name: mosip-api-internal-host
#    value: api-internal.dev.mosip.net
#  - name: keycloak-external-url
#    value: https://iam.dev.mosip.net
#  - name: KEYCLOAK_ADMIN_USER
#    value: admin
    ###keycloak admin password
#  - name: admin-password
#    value: 5wIOk3DgKW
#  - name: mosip_pms_client_secret
#    value: GnUMOiUSJm9oKjYE
#  - name: mosip-esignet-host
#   value: esignet.dev.mosip.net

onboarding:
  modules:
    - name: mobileid
      enabled: false
    - name: mimoto-keybinding
      enabled: true
    - name: mimoto-oidc
      enabled: true

#  configmaps:
#    s3:
#      s3-host: 'http://minio.minio:9000'
#      s3-user-key: 'admin'
#      s3-region: ''
#    onboarder-namespace:
#      ns_mimoto: mimoto
#      ns_esignet: esignet
#      ns_signup: signup
#  secrets:
#    s3:
#      s3-user-secret: 'password'
#  volumes:
#    reports:
#      name: onboarder-reports
#      storageClass: nfs-client
#      accessModes:
#        - ReadWriteMany
#      size: 10Mi
#      existingClaim:
#      # Dir where config and keys are written inside container
#      mountDir: /home/mosip/reports
#      nfs:
#        path: "/srv/nfs/sandbox/onboarding"  # Dir within the nfs server where config repo is cloned/maintained locally.
#        server: "nfs-server"  # Ip address of nfs server.
#  variables:
#    push_reports_to_s3: true
