package io.mosip.mimoto.dto.dpop;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "OpenID4VCI authorization URL built by Mimoto, including dpop_jkt. PKCE state is generated server-side.")
public class IssuerAuthorizeResponse {

    @Schema(description = "Authorization Server URL. Inji Web should open this URL.",
            example = "https://as.example.com/authorize?client_id=...&dpop_jkt=...")
    private String authorizationUrl;

    @Schema(description = "OAuth state generated by Mimoto. Inji Web keys the browser UI session with this value and sends it as the state header on download.",
            example = "Iv~UKBqw_XGsyIT~7GuKrVLFfUvtVSEk3993qSftpm.")
    private String state;
}
